/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.lcsw.sw05;

import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2014-08-19 10:36:45
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class GcpgsjBVO extends SuperVO {
	private UFDate yqxgrq;
	private UFDouble gc;
	private String reserve19;
	private String reserve15;
	private String reserve16;
	private String reserve17;
	private String sjdw;
	private String reserve18;
	private String remark;
	private String pk_jobbasfil;
	private Integer wgyqts;
	private UFDateTime ts;
	private String reserve9;
	private UFDouble reserve8;
	private UFDouble reserve5;
	private String reserve4;
	private UFDouble reserve7;
	private String pk_bzxx;
	private Integer dr;
	private UFDouble reserve6;
	private String reserve1;
	private String reserve3;
	private String reserve2;
	private String reserve20;
	private String pk_gcpgsjbid;
	private String yqxgr;
	private Integer sbgs;
	private String reserve10;
	private String swsgdw;
	private String reserve14;
	private Integer sgts;
	private String reserve13;
	private String pk_gcpgsjhid;
	private String reserve12;
	private String snsgdw;
	private String reserve11;
	private String pk_bzsq;
	private String pk_corp;

	public static final String PK_CORP = "pk_corp";
	public static final String PK_BZSQ = "pk_bzsq";

	public static final String YQXGRQ = "yqxgrq";
	public static final String GC = "gc";
	public static final String RESERVE19 = "reserve19";
	public static final String RESERVE15 = "reserve15";
	public static final String RESERVE16 = "reserve16";
	public static final String RESERVE17 = "reserve17";
	public static final String SJDW = "sjdw";
	public static final String RESERVE18 = "reserve18";
	public static final String REMARK = "remark";
	public static final String PK_JOBBASFIL = "pk_jobbasfil";
	public static final String WGYQTS = "wgyqts";
	public static final String RESERVE9 = "reserve9";
	public static final String RESERVE8 = "reserve8";
	public static final String RESERVE5 = "reserve5";
	public static final String RESERVE4 = "reserve4";
	public static final String RESERVE7 = "reserve7";
	public static final String PK_BZXX = "pk_bzxx";
	public static final String RESERVE6 = "reserve6";
	public static final String RESERVE1 = "reserve1";
	public static final String RESERVE3 = "reserve3";
	public static final String RESERVE2 = "reserve2";
	public static final String RESERVE20 = "reserve20";
	public static final String PK_GCPGSJBID = "pk_gcpgsjbid";
	public static final String YQXGR = "yqxgr";
	public static final String SBGS = "sbgs";
	public static final String RESERVE10 = "reserve10";
	public static final String SWSGDW = "swsgdw";
	public static final String RESERVE14 = "reserve14";
	public static final String SGTS = "sgts";
	public static final String RESERVE13 = "reserve13";
	public static final String PK_GCPGSJHID = "pk_gcpgsjhid";
	public static final String RESERVE12 = "reserve12";
	public static final String SNSGDW = "snsgdw";
	public static final String RESERVE11 = "reserve11";

	/**
	 * 属性pk_corp的Getter方法. 创建日期:2014-08-08 11:00:47
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法. 创建日期:2014-08-08 11:00:47
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {
		this.pk_corp = newPk_corp;
	}

	/**
	 * 
	 * @return String
	 */
	public String getPk_bzsq() {
		return pk_bzsq;
	}

	/**
	 * 
	 * @param newReserve19
	 *            String
	 */
	public void setPk_bzsq(String pk_bzsq) {
		this.pk_bzsq = pk_bzsq;
	}

	/**
	 * 属性yqxgrq的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return UFDate
	 */
	public UFDate getYqxgrq() {
		return yqxgrq;
	}

	/**
	 * 属性yqxgrq的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newYqxgrq
	 *            UFDate
	 */
	public void setYqxgrq(UFDate newYqxgrq) {
		this.yqxgrq = newYqxgrq;
	}

	/**
	 * 属性gc的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return UFDouble
	 */
	public UFDouble getGc() {
		return gc;
	}

	/**
	 * 属性gc的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newGc
	 *            UFDouble
	 */
	public void setGc(UFDouble newGc) {
		this.gc = newGc;
	}

	/**
	 * 属性reserve19的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve19() {
		return reserve19;
	}

	/**
	 * 属性reserve19的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve19
	 *            String
	 */
	public void setReserve19(String newReserve19) {
		this.reserve19 = newReserve19;
	}

	/**
	 * 属性reserve15的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve15() {
		return reserve15;
	}

	/**
	 * 属性reserve15的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve15
	 *            String
	 */
	public void setReserve15(String newReserve15) {
		this.reserve15 = newReserve15;
	}

	/**
	 * 属性reserve16的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve16() {
		return reserve16;
	}

	/**
	 * 属性reserve16的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve16
	 *            String
	 */
	public void setReserve16(String newReserve16) {
		this.reserve16 = newReserve16;
	}

	/**
	 * 属性reserve17的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve17() {
		return reserve17;
	}

	/**
	 * 属性reserve17的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve17
	 *            String
	 */
	public void setReserve17(String newReserve17) {
		this.reserve17 = newReserve17;
	}

	/**
	 * 属性sjdw的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getSjdw() {
		return sjdw;
	}

	/**
	 * 属性sjdw的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newSjdw
	 *            String
	 */
	public void setSjdw(String newSjdw) {
		this.sjdw = newSjdw;
	}

	/**
	 * 属性reserve18的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve18() {
		return reserve18;
	}

	/**
	 * 属性reserve18的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve18
	 *            String
	 */
	public void setReserve18(String newReserve18) {
		this.reserve18 = newReserve18;
	}

	/**
	 * 属性remark的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * 属性remark的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newRemark
	 *            String
	 */
	public void setRemark(String newRemark) {
		this.remark = newRemark;
	}

	/**
	 * 属性pk_jobbasfil的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getPk_jobbasfil() {
		return pk_jobbasfil;
	}

	/**
	 * 属性pk_jobbasfil的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newPk_jobbasfil
	 *            String
	 */
	public void setPk_jobbasfil(String newPk_jobbasfil) {
		this.pk_jobbasfil = newPk_jobbasfil;
	}

	/**
	 * 属性wgyqts的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return UFDouble
	 */
	public Integer getWgyqts() {
		return wgyqts;
	}

	/**
	 * 属性wgyqts的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newWgyqts
	 *            UFDouble
	 */
	public void setWgyqts(Integer newWgyqts) {
		this.wgyqts = newWgyqts;
	}

	/**
	 * 属性ts的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * 属性reserve9的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve9() {
		return reserve9;
	}

	/**
	 * 属性reserve9的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve9
	 *            String
	 */
	public void setReserve9(String newReserve9) {
		this.reserve9 = newReserve9;
	}

	/**
	 * 属性reserve8的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return UFDouble
	 */
	public UFDouble getReserve8() {
		return reserve8;
	}

	/**
	 * 属性reserve8的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve8
	 *            UFDouble
	 */
	public void setReserve8(UFDouble newReserve8) {
		this.reserve8 = newReserve8;
	}

	/**
	 * 属性reserve5的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return UFDouble
	 */
	public UFDouble getReserve5() {
		return reserve5;
	}

	/**
	 * 属性reserve5的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve5
	 *            UFDouble
	 */
	public void setReserve5(UFDouble newReserve5) {
		this.reserve5 = newReserve5;
	}

	/**
	 * 属性reserve4的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve4() {
		return reserve4;
	}

	/**
	 * 属性reserve4的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve4
	 *            String
	 */
	public void setReserve4(String newReserve4) {
		this.reserve4 = newReserve4;
	}

	/**
	 * 属性reserve7的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return UFDouble
	 */
	public UFDouble getReserve7() {
		return reserve7;
	}

	/**
	 * 属性reserve7的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve7
	 *            UFDouble
	 */
	public void setReserve7(UFDouble newReserve7) {
		this.reserve7 = newReserve7;
	}

	/**
	 * 属性pk_bzxx的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getPk_bzxx() {
		return pk_bzxx;
	}

	/**
	 * 属性pk_bzxx的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newPk_bzxx
	 *            String
	 */
	public void setPk_bzxx(String newPk_bzxx) {
		this.pk_bzxx = newPk_bzxx;
	}

	/**
	 * 属性dr的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return UFDouble
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newDr
	 *            UFDouble
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * 属性reserve6的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return UFDouble
	 */
	public UFDouble getReserve6() {
		return reserve6;
	}

	/**
	 * 属性reserve6的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve6
	 *            UFDouble
	 */
	public void setReserve6(UFDouble newReserve6) {
		this.reserve6 = newReserve6;
	}

	/**
	 * 属性reserve1的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve1() {
		return reserve1;
	}

	/**
	 * 属性reserve1的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve1
	 *            String
	 */
	public void setReserve1(String newReserve1) {
		this.reserve1 = newReserve1;
	}

	/**
	 * 属性reserve3的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve3() {
		return reserve3;
	}

	/**
	 * 属性reserve3的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve3
	 *            String
	 */
	public void setReserve3(String newReserve3) {
		this.reserve3 = newReserve3;
	}

	/**
	 * 属性reserve2的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve2() {
		return reserve2;
	}

	/**
	 * 属性reserve2的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve2
	 *            String
	 */
	public void setReserve2(String newReserve2) {
		this.reserve2 = newReserve2;
	}

	/**
	 * 属性reserve20的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve20() {
		return reserve20;
	}

	/**
	 * 属性reserve20的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve20
	 *            String
	 */
	public void setReserve20(String newReserve20) {
		this.reserve20 = newReserve20;
	}

	/**
	 * 属性pk_gcpgsjbid的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getPk_gcpgsjbid() {
		return pk_gcpgsjbid;
	}

	/**
	 * 属性pk_gcpgsjbid的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newPk_gcpgsjbid
	 *            String
	 */
	public void setPk_gcpgsjbid(String newPk_gcpgsjbid) {
		this.pk_gcpgsjbid = newPk_gcpgsjbid;
	}

	/**
	 * 属性yqxgr的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getYqxgr() {
		return yqxgr;
	}

	/**
	 * 属性yqxgr的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newYqxgr
	 *            String
	 */
	public void setYqxgr(String newYqxgr) {
		this.yqxgr = newYqxgr;
	}

	/**
	 * 属性sbgs的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return UFDouble
	 */
	public Integer getSbgs() {
		return sbgs;
	}

	/**
	 * 属性sbgs的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newSbgs
	 *            UFDouble
	 */
	public void setSbgs(Integer newSbgs) {
		this.sbgs = newSbgs;
	}

	/**
	 * 属性reserve10的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve10() {
		return reserve10;
	}

	/**
	 * 属性reserve10的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve10
	 *            String
	 */
	public void setReserve10(String newReserve10) {
		this.reserve10 = newReserve10;
	}

	/**
	 * 属性swsgdw的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getSwsgdw() {
		return swsgdw;
	}

	/**
	 * 属性swsgdw的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newSwsgdw
	 *            String
	 */
	public void setSwsgdw(String newSwsgdw) {
		this.swsgdw = newSwsgdw;
	}

	/**
	 * 属性reserve14的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve14() {
		return reserve14;
	}

	/**
	 * 属性reserve14的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve14
	 *            String
	 */
	public void setReserve14(String newReserve14) {
		this.reserve14 = newReserve14;
	}

	/**
	 * 属性sgts的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return UFDouble
	 */
	public Integer getSgts() {
		return sgts;
	}

	/**
	 * 属性sgts的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newSgts
	 *            UFDouble
	 */
	public void setSgts(Integer newSgts) {
		this.sgts = newSgts;
	}

	/**
	 * 属性reserve13的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve13() {
		return reserve13;
	}

	/**
	 * 属性reserve13的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve13
	 *            String
	 */
	public void setReserve13(String newReserve13) {
		this.reserve13 = newReserve13;
	}

	/**
	 * 属性pk_gcpgsjhid的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getPk_gcpgsjhid() {
		return pk_gcpgsjhid;
	}

	/**
	 * 属性pk_gcpgsjhid的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newPk_gcpgsjhid
	 *            String
	 */
	public void setPk_gcpgsjhid(String newPk_gcpgsjhid) {
		this.pk_gcpgsjhid = newPk_gcpgsjhid;
	}

	/**
	 * 属性reserve12的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve12() {
		return reserve12;
	}

	/**
	 * 属性reserve12的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve12
	 *            String
	 */
	public void setReserve12(String newReserve12) {
		this.reserve12 = newReserve12;
	}

	/**
	 * 属性snsgdw的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getSnsgdw() {
		return snsgdw;
	}

	/**
	 * 属性snsgdw的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newSnsgdw
	 *            String
	 */
	public void setSnsgdw(String newSnsgdw) {
		this.snsgdw = newSnsgdw;
	}

	/**
	 * 属性reserve11的Getter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @return String
	 */
	public String getReserve11() {
		return reserve11;
	}

	/**
	 * 属性reserve11的Setter方法. 创建日期:2014-08-19 10:36:45
	 * 
	 * @param newReserve11
	 *            String
	 */
	public void setReserve11(String newReserve11) {
		this.reserve11 = newReserve11;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2014-08-19 10:36:45
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2014-08-19 10:36:45
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_gcpgsjbid";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2014-08-19 10:36:45
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "LCSW_GCPGSJ_B";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2014-08-19 10:36:45
	 */
	public GcpgsjBVO() {
		super();
	}
}
