/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.lcsw.sw06;

import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2014-08-28 10:37:40
 * 
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class FbyjazVO extends SuperVO {
	private String vlastbillid;
	private UFDouble ysszje;
	private String remark;
	private UFDouble yfk;
	private String vlastbillrowid;
	private String vapproveid;
	private String reserve9;
	private UFDouble reserve8;
	private UFDouble reserve5;
	private String reserve4;
	private UFDouble reserve7;
	private String hth;
	private Integer dr;
	private UFDouble reserve6;
	private UFDouble jdk;
	private String reserve1;
	private String reserve3;
	private String pk_busitype;
	private String reserve2;
	private String modifier;
	private UFDate kfprq;
	private String vsourcebillid;
	private UFDate dmodify;
	private UFDouble gsczje;
	private String vsourcebillrowid;
	private UFBoolean sfxyyjjs;
	private String voperatorid;
	private UFDouble yhczje;
	private UFDate yfkfkrq;
	private String vlastbillno;
	private String reserve10;
	private String gcxz;
	private UFDate dbilldate;
	private String reserve14;
	private String reserve13;
	private String pk_fbyjaz;
	private String reserve12;
	private String reserve11;
	private UFBoolean sfysght;
	private String reserve19;
	private UFBoolean sfykfp;
	private String reserve15;
	private String reserve16;
	private String pk_billtype;
	private String reserve17;
	private String reserve18;
	private String pk_jobbasfil;
	private UFDateTime ts;
	private String vsourcebilltype;
	private String vapprovenote;
	private String pk_corp;
	private String vbillcode;
	private UFDate jdkfkrq;
	private UFDate jsrq;
	private String reserve20;
	private String vlastbilltype;
	private UFDate dmakedate;
	private Integer vbillstatus;
	private UFBoolean sfsbgj;
	private UFDate jzlrq;
	private UFDouble yhysk;
	private UFDouble yhjsk;
	private UFDate dapprovedate;
	
	private String sjth;
	private UFDate zbsqdrq;
	private UFDouble zbj;
	private UFDate szbjrq;
	private UFBoolean sfyjaz;
	private UFDate yjazrq;
	private UFDate htqdrq;
	
	public UFDate getHtqdrq() {
		return htqdrq;
	}

	public void setHtqdrq(UFDate htqdrq) {
		this.htqdrq = htqdrq;
	}

	public String getSjth() {
		return sjth;
	}

	public void setSjth(String sjth) {
		this.sjth = sjth;
	}

	public UFDate getZbsqdrq() {
		return zbsqdrq;
	}

	public void setZbsqdrq(UFDate zbsqdrq) {
		this.zbsqdrq = zbsqdrq;
	}

	public UFDouble getZbj() {
		return zbj;
	}

	public void setZbj(UFDouble zbj) {
		this.zbj = zbj;
	}

	public UFDate getSzbjrq() {
		return szbjrq;
	}

	public void setSzbjrq(UFDate szbjrq) {
		this.szbjrq = szbjrq;
	}

	public UFBoolean getSfyjaz() {
		return sfyjaz;
	}

	public void setSfyjaz(UFBoolean sfyjaz) {
		this.sfyjaz = sfyjaz;
	}

	public UFDate getYjazrq() {
		return yjazrq;
	}

	public void setYjazrq(UFDate yjazrq) {
		this.yjazrq = yjazrq;
	}

	public void setLrrq(UFDate lrrq) {
		this.lrrq = lrrq;
	}

	public static final String SJTH = "sjth";
	public static final String ZBSQDRQ = "zbsqdrq";
	public static final String ZBJ = "zbj";
	public static final String SZBJRQ = "szbjrq";
	public static final String SFYJAZ = "sfyjaz";
	public static final String YJAZRQ = "yjazrq";
	public static final String HTQDRQ = "htqdrq";
	
	
	public static final String VLASTBILLID = "vlastbillid";
	public static final String YSSZJE = "ysszje";
	public static final String REMARK = "remark";
	public static final String YFK = "yfk";
	public static final String VLASTBILLROWID = "vlastbillrowid";
	public static final String VAPPROVEID = "vapproveid";
	public static final String RESERVE9 = "reserve9";
	public static final String RESERVE8 = "reserve8";
	public static final String RESERVE5 = "reserve5";
	public static final String RESERVE4 = "reserve4";
	public static final String RESERVE7 = "reserve7";
	public static final String HTH = "hth";
	public static final String RESERVE6 = "reserve6";
	public static final String JDK = "jdk";
	public static final String RESERVE1 = "reserve1";
	public static final String RESERVE3 = "reserve3";
	public static final String PK_BUSITYPE = "pk_busitype";
	public static final String RESERVE2 = "reserve2";
	public static final String MODIFIER = "modifier";
	public static final String KFPRQ = "kfprq";
	public static final String VSOURCEBILLID = "vsourcebillid";
	public static final String DMODIFY = "dmodify";
	public static final String GSCZJE = "gsczje";
	public static final String VSOURCEBILLROWID = "vsourcebillrowid";
	public static final String SFXYYJJS = "sfxyyjjs";
	public static final String VOPERATORID = "voperatorid";
	public static final String YHCZJE = "yhczje";
	public static final String YFKFKRQ = "yfkfkrq";
	public static final String VLASTBILLNO = "vlastbillno";
	public static final String RESERVE10 = "reserve10";
	public static final String GCXZ = "gcxz";
	public static final String DBILLDATE = "dbilldate";
	public static final String RESERVE14 = "reserve14";
	public static final String RESERVE13 = "reserve13";
	public static final String PK_FBYJAZ = "pk_fbyjaz";
	public static final String RESERVE12 = "reserve12";
	public static final String RESERVE11 = "reserve11";
	public static final String SFYSGHT = "sfysght";
	public static final String RESERVE19 = "reserve19";
	public static final String SFYKFP = "sfykfp";
	public static final String RESERVE15 = "reserve15";
	public static final String RESERVE16 = "reserve16";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String RESERVE17 = "reserve17";
	public static final String RESERVE18 = "reserve18";
	public static final String PK_JOBBASFIL = "pk_jobbasfil";
	public static final String VSOURCEBILLTYPE = "vsourcebilltype";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String PK_CORP = "pk_corp";
	public static final String VBILLCODE = "vbillcode";
	public static final String JDKFKRQ = "jdkfkrq";
	public static final String JSRQ = "jsrq";
	public static final String RESERVE20 = "reserve20";
	public static final String VLASTBILLTYPE = "vlastbilltype";
	public static final String DMAKEDATE = "dmakedate";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String SFSBGJ = "sfsbgj";
	public static final String JZLRQ = "jzlrq";
	public static final String YHYSK = "yhysk";
	public static final String YHJSK = "yhjsk";
	public static final String DAPPROVEDATE = "dapprovedate";

	/**
	 * 属性vlastbillid的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getVlastbillid() {
		return vlastbillid;
	}

	/**
	 * 属性vlastbillid的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newVlastbillid
	 *            String
	 */
	public void setVlastbillid(String newVlastbillid) {
		this.vlastbillid = newVlastbillid;
	}

	/**
	 * 属性ysszje的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFDouble getYsszje() {
		return ysszje;
	}

	/**
	 * 属性ysszje的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newYsszje
	 *            UFDouble
	 */
	public void setYsszje(UFDouble newYsszje) {
		this.ysszje = newYsszje;
	}

	/**
	 * 属性remark的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * 属性remark的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newRemark
	 *            String
	 */
	public void setRemark(String newRemark) {
		this.remark = newRemark;
	}

	/**
	 * 属性yfk的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFDouble getYfk() {
		return yfk;
	}

	/**
	 * 属性yfk的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newYfk
	 *            UFDouble
	 */
	public void setYfk(UFDouble newYfk) {
		this.yfk = newYfk;
	}

	/**
	 * 属性vlastbillrowid的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getVlastbillrowid() {
		return vlastbillrowid;
	}

	/**
	 * 属性vlastbillrowid的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newVlastbillrowid
	 *            String
	 */
	public void setVlastbillrowid(String newVlastbillrowid) {
		this.vlastbillrowid = newVlastbillrowid;
	}

	/**
	 * 属性vapproveid的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getVapproveid() {
		return vapproveid;
	}

	/**
	 * 属性vapproveid的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newVapproveid
	 *            String
	 */
	public void setVapproveid(String newVapproveid) {
		this.vapproveid = newVapproveid;
	}

	/**
	 * 属性reserve9的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve9() {
		return reserve9;
	}

	/**
	 * 属性reserve9的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve9
	 *            String
	 */
	public void setReserve9(String newReserve9) {
		this.reserve9 = newReserve9;
	}

	/**
	 * 属性reserve8的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFDouble getReserve8() {
		return reserve8;
	}

	/**
	 * 属性reserve8的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve8
	 *            UFDouble
	 */
	public void setReserve8(UFDouble newReserve8) {
		this.reserve8 = newReserve8;
	}

	/**
	 * 属性reserve5的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFDouble getReserve5() {
		return reserve5;
	}

	/**
	 * 属性reserve5的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve5
	 *            UFDouble
	 */
	public void setReserve5(UFDouble newReserve5) {
		this.reserve5 = newReserve5;
	}

	/**
	 * 属性reserve4的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve4() {
		return reserve4;
	}

	/**
	 * 属性reserve4的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve4
	 *            String
	 */
	public void setReserve4(String newReserve4) {
		this.reserve4 = newReserve4;
	}

	/**
	 * 属性reserve7的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFDouble getReserve7() {
		return reserve7;
	}

	/**
	 * 属性reserve7的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve7
	 *            UFDouble
	 */
	public void setReserve7(UFDouble newReserve7) {
		this.reserve7 = newReserve7;
	}

	/**
	 * 属性hth的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getHth() {
		return hth;
	}

	/**
	 * 属性hth的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newHth
	 *            String
	 */
	public void setHth(String newHth) {
		this.hth = newHth;
	}

	/**
	 * 属性dr的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newDr
	 *            UFDouble
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * 属性reserve6的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFDouble getReserve6() {
		return reserve6;
	}

	/**
	 * 属性reserve6的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve6
	 *            UFDouble
	 */
	public void setReserve6(UFDouble newReserve6) {
		this.reserve6 = newReserve6;
	}

	/**
	 * 属性jdk的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFDouble getJdk() {
		return jdk;
	}

	/**
	 * 属性jdk的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newJdk
	 *            UFDouble
	 */
	public void setJdk(UFDouble newJdk) {
		this.jdk = newJdk;
	}

	/**
	 * 属性reserve1的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve1() {
		return reserve1;
	}

	/**
	 * 属性reserve1的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve1
	 *            String
	 */
	public void setReserve1(String newReserve1) {
		this.reserve1 = newReserve1;
	}

	/**
	 * 属性reserve3的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve3() {
		return reserve3;
	}

	/**
	 * 属性reserve3的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve3
	 *            String
	 */
	public void setReserve3(String newReserve3) {
		this.reserve3 = newReserve3;
	}

	/**
	 * 属性pk_busitype的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getPk_busitype() {
		return pk_busitype;
	}

	/**
	 * 属性pk_busitype的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newPk_busitype
	 *            String
	 */
	public void setPk_busitype(String newPk_busitype) {
		this.pk_busitype = newPk_busitype;
	}

	/**
	 * 属性reserve2的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve2() {
		return reserve2;
	}

	/**
	 * 属性reserve2的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve2
	 *            String
	 */
	public void setReserve2(String newReserve2) {
		this.reserve2 = newReserve2;
	}

	/**
	 * 属性modifier的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getModifier() {
		return modifier;
	}

	/**
	 * 属性modifier的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newModifier
	 *            String
	 */
	public void setModifier(String newModifier) {
		this.modifier = newModifier;
	}

	/**
	 * 属性kfprq的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDate
	 */
	public UFDate getKfprq() {
		return kfprq;
	}

	/**
	 * 属性kfprq的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newKfprq
	 *            UFDate
	 */
	public void setKfprq(UFDate newKfprq) {
		this.kfprq = newKfprq;
	}

	/**
	 * 属性vsourcebillid的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getVsourcebillid() {
		return vsourcebillid;
	}

	/**
	 * 属性vsourcebillid的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newVsourcebillid
	 *            String
	 */
	public void setVsourcebillid(String newVsourcebillid) {
		this.vsourcebillid = newVsourcebillid;
	}

	/**
	 * 属性dmodify的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDate
	 */
	public UFDate getDmodify() {
		return dmodify;
	}

	/**
	 * 属性dmodify的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newDmodify
	 *            UFDate
	 */
	public void setDmodify(UFDate newDmodify) {
		this.dmodify = newDmodify;
	}

	/**
	 * 属性gsczje的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFDouble getGsczje() {
		return gsczje;
	}

	/**
	 * 属性gsczje的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newGsczje
	 *            UFDouble
	 */
	public void setGsczje(UFDouble newGsczje) {
		this.gsczje = newGsczje;
	}

	/**
	 * 属性vsourcebillrowid的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getVsourcebillrowid() {
		return vsourcebillrowid;
	}

	/**
	 * 属性vsourcebillrowid的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newVsourcebillrowid
	 *            String
	 */
	public void setVsourcebillrowid(String newVsourcebillrowid) {
		this.vsourcebillrowid = newVsourcebillrowid;
	}

	/**
	 * 属性sfxyyjjs的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFBoolean getSfxyyjjs() {
		return sfxyyjjs;
	}

	/**
	 * 属性sfxyyjjs的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newSfxyyjjs
	 *            UFDouble
	 */
	public void setSfxyyjjs(UFBoolean newSfxyyjjs) {
		this.sfxyyjjs = newSfxyyjjs;
	}

	/**
	 * 属性voperatorid的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getVoperatorid() {
		return voperatorid;
	}

	/**
	 * 属性voperatorid的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newVoperatorid
	 *            String
	 */
	public void setVoperatorid(String newVoperatorid) {
		this.voperatorid = newVoperatorid;
	}

	/**
	 * 属性yhczje的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFDouble getYhczje() {
		return yhczje;
	}

	/**
	 * 属性yhczje的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newYhczje
	 *            UFDouble
	 */
	public void setYhczje(UFDouble newYhczje) {
		this.yhczje = newYhczje;
	}

	/**
	 * 属性yfkfkrq的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDate
	 */
	public UFDate getYfkfkrq() {
		return yfkfkrq;
	}

	/**
	 * 属性yfkfkrq的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newYfkfkrq
	 *            UFDate
	 */
	public void setYfkfkrq(UFDate newYfkfkrq) {
		this.yfkfkrq = newYfkfkrq;
	}

	/**
	 * 属性vlastbillno的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getVlastbillno() {
		return vlastbillno;
	}

	/**
	 * 属性vlastbillno的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newVlastbillno
	 *            String
	 */
	public void setVlastbillno(String newVlastbillno) {
		this.vlastbillno = newVlastbillno;
	}

	/**
	 * 属性reserve10的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve10() {
		return reserve10;
	}

	/**
	 * 属性reserve10的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve10
	 *            String
	 */
	public void setReserve10(String newReserve10) {
		this.reserve10 = newReserve10;
	}

	/**
	 * 属性gcxz的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getGcxz() {
		return gcxz;
	}

	/**
	 * 属性gcxz的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newGcxz
	 *            String
	 */
	public void setGcxz(String newGcxz) {
		this.gcxz = newGcxz;
	}

	/**
	 * 属性dbilldate的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDate
	 */
	public UFDate getDbilldate() {
		return dbilldate;
	}

	/**
	 * 属性dbilldate的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newDbilldate
	 *            UFDate
	 */
	public void setDbilldate(UFDate newDbilldate) {
		this.dbilldate = newDbilldate;
	}

	/**
	 * 属性reserve14的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve14() {
		return reserve14;
	}

	/**
	 * 属性reserve14的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve14
	 *            String
	 */
	public void setReserve14(String newReserve14) {
		this.reserve14 = newReserve14;
	}

	/**
	 * 属性reserve13的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve13() {
		return reserve13;
	}

	/**
	 * 属性reserve13的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve13
	 *            String
	 */
	public void setReserve13(String newReserve13) {
		this.reserve13 = newReserve13;
	}

	/**
	 * 属性pk_fbyjaz的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getPk_fbyjaz() {
		return pk_fbyjaz;
	}

	/**
	 * 属性pk_fbyjaz的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newpk_fbyjaz
	 *            String
	 */
	public void setPk_fbyjaz(String newpk_fbyjaz) {
		this.pk_fbyjaz = newpk_fbyjaz;
	}

	/**
	 * 属性reserve12的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve12() {
		return reserve12;
	}

	/**
	 * 属性reserve12的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve12
	 *            String
	 */
	public void setReserve12(String newReserve12) {
		this.reserve12 = newReserve12;
	}

	/**
	 * 属性reserve11的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve11() {
		return reserve11;
	}

	/**
	 * 属性reserve11的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve11
	 *            String
	 */
	public void setReserve11(String newReserve11) {
		this.reserve11 = newReserve11;
	}

	/**
	 * 属性sfysght的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFBoolean getSfysght() {
		return sfysght;
	}

	/**
	 * 属性sfysght的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newSfysght
	 *            UFDouble
	 */
	public void setSfysght(UFBoolean newSfysght) {
		this.sfysght = newSfysght;
	}

	/**
	 * 属性reserve19的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve19() {
		return reserve19;
	}

	/**
	 * 属性reserve19的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve19
	 *            String
	 */
	public void setReserve19(String newReserve19) {
		this.reserve19 = newReserve19;
	}

	/**
	 * 属性sfykfp的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFBoolean getSfykfp() {
		return sfykfp;
	}

	/**
	 * 属性sfykfp的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newSfykfp
	 *            UFDouble
	 */
	public void setSfykfp(UFBoolean newSfykfp) {
		this.sfykfp = newSfykfp;
	}

	/**
	 * 属性reserve15的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve15() {
		return reserve15;
	}

	/**
	 * 属性reserve15的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve15
	 *            String
	 */
	public void setReserve15(String newReserve15) {
		this.reserve15 = newReserve15;
	}

	/**
	 * 属性reserve16的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve16() {
		return reserve16;
	}

	/**
	 * 属性reserve16的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve16
	 *            String
	 */
	public void setReserve16(String newReserve16) {
		this.reserve16 = newReserve16;
	}

	/**
	 * 属性pk_billtype的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getPk_billtype() {
		return pk_billtype;
	}

	/**
	 * 属性pk_billtype的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newPk_billtype
	 *            String
	 */
	public void setPk_billtype(String newPk_billtype) {
		this.pk_billtype = newPk_billtype;
	}

	/**
	 * 属性reserve17的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve17() {
		return reserve17;
	}

	/**
	 * 属性reserve17的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve17
	 *            String
	 */
	public void setReserve17(String newReserve17) {
		this.reserve17 = newReserve17;
	}

	/**
	 * 属性reserve18的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve18() {
		return reserve18;
	}

	/**
	 * 属性reserve18的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve18
	 *            String
	 */
	public void setReserve18(String newReserve18) {
		this.reserve18 = newReserve18;
	}

	/**
	 * 属性pk_jobbasfil的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getPk_jobbasfil() {
		return pk_jobbasfil;
	}

	/**
	 * 属性pk_jobbasfil的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newPk_jobbasfil
	 *            String
	 */
	public void setPk_jobbasfil(String newPk_jobbasfil) {
		this.pk_jobbasfil = newPk_jobbasfil;
	}

	/**
	 * 属性ts的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * 属性vsourcebilltype的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getVsourcebilltype() {
		return vsourcebilltype;
	}

	/**
	 * 属性vsourcebilltype的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newVsourcebilltype
	 *            String
	 */
	public void setVsourcebilltype(String newVsourcebilltype) {
		this.vsourcebilltype = newVsourcebilltype;
	}

	/**
	 * 属性vapprovenote的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getVapprovenote() {
		return vapprovenote;
	}

	/**
	 * 属性vapprovenote的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newVapprovenote
	 *            String
	 */
	public void setVapprovenote(String newVapprovenote) {
		this.vapprovenote = newVapprovenote;
	}

	/**
	 * 属性pk_corp的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {
		this.pk_corp = newPk_corp;
	}

	/**
	 * 属性vbillcode的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getVbillcode() {
		return vbillcode;
	}

	/**
	 * 属性vbillcode的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newVbillcode
	 *            String
	 */
	public void setVbillcode(String newVbillcode) {
		this.vbillcode = newVbillcode;
	}

	/**
	 * 属性jdkfkrq的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDate
	 */
	public UFDate getJdkfkrq() {
		return jdkfkrq;
	}

	/**
	 * 属性jdkfkrq的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newJdkfkrq
	 *            UFDate
	 */
	public void setJdkfkrq(UFDate newJdkfkrq) {
		this.jdkfkrq = newJdkfkrq;
	}

	/**
	 * 属性jsrq的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDate
	 */
	public UFDate getJsrq() {
		return jsrq;
	}

	/**
	 * 属性jsrq的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newJsrq
	 *            UFDate
	 */
	public void setJsrq(UFDate newJsrq) {
		this.jsrq = newJsrq;
	}

	/**
	 * 属性reserve20的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getReserve20() {
		return reserve20;
	}

	/**
	 * 属性reserve20的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newReserve20
	 *            String
	 */
	public void setReserve20(String newReserve20) {
		this.reserve20 = newReserve20;
	}

	/**
	 * 属性vlastbilltype的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return String
	 */
	public String getVlastbilltype() {
		return vlastbilltype;
	}

	/**
	 * 属性vlastbilltype的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newVlastbilltype
	 *            String
	 */
	public void setVlastbilltype(String newVlastbilltype) {
		this.vlastbilltype = newVlastbilltype;
	}

	/**
	 * 属性dmakedate的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDate
	 */
	public UFDate getDmakedate() {
		return dmakedate;
	}

	/**
	 * 属性dmakedate的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newDmakedate
	 *            UFDate
	 */
	public void setDmakedate(UFDate newDmakedate) {
		this.dmakedate = newDmakedate;
	}

	/**
	 * 属性vbillstatus的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * 属性vbillstatus的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newVbillstatus
	 *            UFDouble
	 */
	public void setVbillstatus(Integer newVbillstatus) {
		this.vbillstatus = newVbillstatus;
	}

	/**
	 * 属性sfsbgj的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFBoolean getSfsbgj() {
		return sfsbgj;
	}

	/**
	 * 属性sfsbgj的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newSfsbgj
	 *            UFDouble
	 */
	public void setSfsbgj(UFBoolean newSfsbgj) {
		this.sfsbgj = newSfsbgj;
	}

	/**
	 * 属性jzlrq的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDate
	 */
	public UFDate getJzlrq() {
		return jzlrq;
	}

	/**
	 * 属性jzlrq的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newJzlrq
	 *            UFDate
	 */
	public void setJzlrq(UFDate newJzlrq) {
		this.jzlrq = newJzlrq;
	}

	/**
	 * 属性yhysk的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDouble
	 */
	public UFDouble getYhysk() {
		return yhysk;
	}

	/**
	 * 属性yhysk的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newYhysk
	 *            UFDouble
	 */
	public void setYhysk(UFDouble newYhysk) {
		this.yhysk = newYhysk;
	}

	/**
	 * 属性jsk的Getter方法. 创建日期:2014-09-18 11:05:59
	 * 
	 * @return UFDouble
	 */
	public UFDouble getYhjsk() {
		return yhjsk;
	}

	/**
	 * 属性jsk的Setter方法. 创建日期:2014-09-18 11:05:59
	 * 
	 * @param newJsk
	 *            UFDouble
	 */
	public void setYhjsk(UFDouble yhjsk) {
		this.yhjsk = yhjsk;
	}

	/**
	 * 属性dapprovedate的Getter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @return UFDate
	 */
	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	/**
	 * 属性dapprovedate的Setter方法. 创建日期:2014-08-28 10:37:40
	 * 
	 * @param newDapprovedate
	 *            UFDate
	 */
	public void setDapprovedate(UFDate newDapprovedate) {
		this.dapprovedate = newDapprovedate;
	}

	private UFDouble sgdwjsk;
	public static final String SGDWJSK = "sgdwjsk";

	/**
	 * 属性jsk的Getter方法. 创建日期:2014-09-18 11:05:59
	 * 
	 * @return UFDouble
	 */
	public UFDouble getSgdwjsk() {
		return sgdwjsk;
	}

	/**
	 * 属性jsk的Setter方法. 创建日期:2014-09-18 11:05:59
	 * 
	 * @param newJsk
	 *            UFDouble
	 */
	public void setSgdwjsk(UFDouble sgdwjsk) {
		this.sgdwjsk = sgdwjsk;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2014-08-28 10:37:40
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2014-08-28 10:37:40
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_fbyjaz";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2014-08-28 10:37:40
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "LCSW_FBYJAZ";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2014-08-28 10:37:40
	 */
	public FbyjazVO() {
		super();
	}

	private UFDate jskfkrq;
	public static final String JSKFKRQ = "jskfkrq";

	/**
	 * 属性gsczje的Getter方法. 创建日期:2014-09-18 11:05:59
	 * 
	 * @return UFDouble
	 */
	public UFDate getJskfkrq() {
		return jskfkrq;
	}

	/**
	 * 属性gsczje的Setter方法. 创建日期:2014-09-18 11:05:59
	 * 
	 * @param newGsczje
	 *            UFDouble
	 */
	public void setJskfkrq(UFDate jskfkrq) {
		this.jskfkrq = jskfkrq;
	}

	private String lrr;
	public static final String LRR = "lrr";

	/**
	 * 属性gsczje的Getter方法. 创建日期:2014-09-18 11:05:59
	 * 
	 * @return UFDouble
	 */
	public String getLrr() {
		return lrr;
	}

	/**
	 * 属性gsczje的Setter方法. 创建日期:2014-09-18 11:05:59
	 * 
	 * @param newGsczje
	 *            UFDouble
	 */
	public void setLrr(String lrr) {
		this.lrr = lrr;
	}

	private UFDate lrrq;
	public static final String LRRQ = "lrrq";

	/**
	 * 属性gsczje的Getter方法. 创建日期:2014-09-18 11:05:59
	 * 
	 * @return UFDouble
	 */
	public UFDate getLrrq() {
		return lrrq;
	}

	/**
	 * 属性gsczje的Setter方法. 创建日期:2014-09-18 11:05:59
	 * 
	 * @param newGsczje
	 *            UFDouble
	 */
	public void setLrr(UFDate lrrq) {
		this.lrrq = lrrq;
	}

}
